Lots of changes, because, well, as they say: "commit late, commit sparsely"

diff --git a/libs/fd-pm-functions b/libs/fd-pm-functions
--- a/libs/fd-pm-functions
+++ b/libs/fd-pm-functions
@@ -1,4 +1,4 @@
-#!SHELL_FULL
+#!/bin/sh
 
 PATH="$PATH:/sbin:/usr/sbin:/usr/local/sbin"
 
@@ -7,9 +7,24 @@ me="$(basename $0)"
 shopt -s nullglob extglob
 
 # turn on kernel options
+#opt() {
+#    [[ -f "$1" ]] || return
+#    tee "$1" <<<"$2" &>/dev/null || echo "[$me] cannot write $2 to $1"
+#}
+
 opt() {
-    [[ -f "$1" ]] || return
-    tee "$1" <<<"$2" &>/dev/null || echo "[$me] cannot write $2 to $1"
+    if [ ! -f "$1" ]; then
+        echo -e -n "${COL_YEL}.${COL_DEF}"
+        return 2
+    fi
+
+    if tee "$1" <<< "$2" &> /dev/null; then
+        echo -e -n "${COL_GRN}.${COL_DEF}"
+        return 0
+    else
+        echo -e -n "${COL_RED}.${COL_DEF}"
+        return 1
+    fi
 }
 
 # unload kernel module
@@ -40,13 +55,30 @@ mod_loaded() {
 # $1 = max file
 # $2 = value
 num_scale() {
-    local scale="$(bc <<< "$(< "$1") / 5")"
-    echo "$(( $scale * $2 ))"
+    #local scale="$(bc <<< "($(< "$1") * 10) / 5")"
+    local scale="$(bc <<< "("$1" * 10) / 5")"
+    echo "$(( ( $scale * $2 ) / 10 ))"
+}
+# max / 5 * val
+# 5 / max * val
+
+elacs_mun() {
+    #local scale="$(bc <<< "($(< "$1") * 10) / 5")"
+    if [ $1 -eq 0 ]; then
+        echo $2
+        exit
+    fi
+    local scale="$(bc <<< "(5 * 1000 + 500) / "$1"")"
+    echo "$(( ( $scale * $2 ) / 1000 ))"
 }
 
 # command
 run() {
-    "$@" &> /dev/null || echo "[$me] cannot run $@"
+    if "$@" &> /dev/null; then
+        echo -e -n "${COL_GRN}.${COL_DEF}"
+    else
+        echo -e -n "${COL_RED}.${COL_DEF}"
+    fi
 }
 
 has_bat() {
@@ -84,6 +116,65 @@ display_readahead() {
 dump () {
     [[ -w "$1" && -r "$1" ]] || return
     echo " -> $1: $(< "$1")"
+}
+
+acdc () {
+    [[ -w "$1" && -r "$1" ]] || return
+    val=$(< "$1")
+
+    if [ "$cur_state" == "1" -a "$val" == "$2" ]; then
+        col=$COL_GRN
+    elif [ "$cur_state" == "0" -a "$val" == "$3" ]; then
+        col=$COL_GRN
+    else
+        col=$COL_RED
+    fi
+    if [ "$val" == "$2" ]; then
+        echo -e -n "${col}^${COL_DEF}"
+    elif [ "$val" == "$3" ]; then
+        echo -e -n "${col}v${COL_DEF}"
+    else
+        echo -e -n "${COL_YEL}?${COL_DEF}"
+    fi
+}
+
+acdc_run () {
+    local ac=$1
+    shift
+    local bat=$1
+    shift
+    val=$($@)
+    if [ "$cur_state" == "1" -a "$val" == "$ac" ]; then
+        col=$COL_GRN
+    elif [ "$cur_state" == "0" -a "$val" == "$bat" ]; then
+        col=$COL_GRN
+    else
+        col=$COL_RED
+    fi
+    if [ "$val" == "$ac" ]; then
+        echo -e -n "${col}^${COL_DEF}"
+    elif [ "$val" == "$bat" ]; then
+        echo -e -n "${col}v${COL_DEF}"
+    else
+        echo -e -n "${COL_YEL}?${COL_DEF}"
+    fi
+}
+
+acdc_test () {
+    if [ "$cur_state" == "1" -a "$1" == "$2" ]; then
+        col=$COL_GRN
+    elif [ "$cur_state" == "0" -a "$1" == "$3" ]; then
+        col=$COL_GRN
+    else
+        col=$COL_RED
+    fi
+    if [ "$1" == "$2" ]; then
+        echo -e -n "${col}^${COL_DEF}"
+    elif [ "$1" == "$3" ]; then
+        echo -e -n "${col}v${COL_DEF}"
+    else
+        echo -e -n "${COL_YEL}?${COL_DEF}"
+    fi
 }
 
 display_module() {
@@ -138,10 +229,15 @@ lock() {
 # $1 = device path
 is_usb_hid() {
     local subdev
+    if [ "${1/\/sys\/bus\/usb\/*/}" != "" ]; then
+        return 1
+    fi
+
     for subdev in $1/*:*; do
         # USB_DEVICE_CLASS 3 = HID
         [[ "$(< "$subdev/bInterfaceClass")" == 03 ]] && return 0
     done
+
     return 1
 }
 
diff --git a/scripts/fd-bright-ctrl b/scripts/fd-bright-ctrl
--- a/scripts/fd-bright-ctrl
+++ b/scripts/fd-bright-ctrl
@@ -2,20 +2,118 @@
 
 source ETCPREFIX/ferrydust/system.rc
 
+if [ "$BRIGHT_PATH" == "" ]; then
+	echo "BRIGHT_PATH not defined, looking for one in /sys/class/backlight/*/brightness"
+	for i in /sys/class/backlight/*/brightness; do
+		BRIGHT_PATH="$(dirname $i)"
+		break
+	done
+	if [ "$BRIGHT_PATH" != "" ]; then
+		echo " * found $BRIGHT_PATH"
+	else
+		echo " * but to no avail"
+		exit 1
+	fi
+fi
+if [ "$BRIGHT_STEPS" == "" ]; then
+	echo "BRIGHT_STEPS not defined"
+	echo " * assuming 10"
+	BRIGHT_STEPS=10
+fi
+
+if [ "$BRIGHT_FADE_STEPS" != "" -a "${1%_*}" == "fade" ]; then
+	BRIGHT_STEPS=$BRIGHT_FADE_STEPS
+fi
+
+if [ ! -d "$BRIGHT_PATH" ]; then
+	echo "Path '$BRIGHT_PATH' not found"
+	exit 1
+fi
+
+if [ -f /tmp/bright ]; then
+	touch /tmp/bright
+	chmod a+r /tmp/bright
+fi
+
 max=$(cat $BRIGHT_PATH/max_brightness)
 step=$(($max/$BRIGHT_STEPS))
 cur=$(cat $BRIGHT_PATH/brightness)
 
-if [ "$1" = "down" ]; then
-    next=$(($cur-$step))
-    if [ $next -lt 1 ]; then
-        next=1
-    fi
-else
-    next=$(($cur+$step))
-    if [ $next -gt $max ]; then
-        next=$max
-    fi
-fi
+up() {
+	local lmax=$1
+	local next=$(($cur+$step))
 
-echo "$next" > $BRIGHT_PATH/brightness
+	if [ $next -gt $lmax ]; then
+		next=$lmax
+	fi
+
+	echo "$next" > $BRIGHT_PATH/brightness
+
+	echo -n $(( ((100000/$(<$BRIGHT_PATH/max_brightness))*$(<$BRIGHT_PATH/brightness))/1000 )) > /tmp/bright
+}
+
+down() {
+	local lmin=$1
+	local next=$(($cur-$step))
+
+	if [ $next -lt $lmin ]; then
+		next=$lmin
+	fi
+
+	echo -n $(((100/$BRIGHT_STEPS)*($next/$step))) > /tmp/bright
+
+	echo "$next" > $BRIGHT_PATH/brightness
+
+	echo -n $(( ((100000/$(<$BRIGHT_PATH/max_brightness))*$(<$BRIGHT_PATH/brightness))/1000 )) > /tmp/bright
+}
+
+case "$1" in
+	up)
+		up $max
+		;;
+	down)
+		down 1
+		;;
+	cur)
+		echo $cur
+		;;
+	cur_step)
+		echo "$(($cur/$step))"
+		;;
+	fade_down)
+		lmin=${2:-1}
+		if [ $cur -gt $lmin ]; then
+			down $lmin
+		else
+			exit 255
+		fi
+		;;
+	fade_up)
+		lmax=${2:-$max}
+		if [ $cur -lt $lmax ]; then
+			up $lmax
+		else
+			exit 255
+		fi
+		;;
+	set)
+		val=$2
+		if [ "$val" -gt $max ]; then
+			val=$max
+		elif [ "$val" -lt 1 ]; then
+			val=1
+		fi
+		echo "$val" > $BRIGHT_PATH/brightness
+		;;
+	set_step)
+		val=$(($2 * $step))
+		if [ "$val" -gt $max ]; then
+			val=$max
+		elif [ "$val" -lt 1 ]; then
+			val=1
+		fi
+		echo "$val" > $BRIGHT_PATH/brightness
+		;;
+	*)
+esac
+
diff --git a/scripts/fd-mount b/scripts/fd-mount
--- a/scripts/fd-mount
+++ b/scripts/fd-mount
@@ -1,46 +1,76 @@
 #!SHELL_FULL
 
+source LIBPREFIX/fd-functions
 source ETCPREFIX/ferrydust/system.rc
+
+udiskie_umount_wrapper() {
+    local un="$(whoami)"
+    udiskie-umount "/run/media/$un/$1"
+
+}
+
+if [ "$MOUNT_THING" == "udiskie" ]; then
+    mount_cmd="udiskie-mount"
+    umount_cmd="udiskie_umount_wrapper"
+elif [ "$MOUNT_THING" == "pmount" ]; then
+    mount_cmd="pmount"
+    umount_cmd="pumount"
+else
+    echo "MOUNT_THING setting \"$MOUNT_THING\" invalid"
+    exit 1
+fi
 
 case "$1" in
     mount)
-        c=0
-        for i in $(mount | cut -d " " -f 1); do
-            mounted[$c]="$i"
-            let c++
-        done
-        for i in ${MOUNT_DEVS[@]}; do
-            for ii in /dev/${i}*; do
-                if [ -b "$ii" ]; then
-                    blocked=0
-                    for iii in ${MOUNT_BLOCK[@]}; do
-                        if [ $(echo $ii | grep $iii | wc -l) -gt 0 ]; then blocked=1; fi
-                    done
-                    for iii in ${mounted[@]}; do
-                        if [ "$iii" == "$ii" ]; then blocked=1; fi
-                    done
-                    if [ $blocked -eq 0 ]; then
-                        devices="${devices}${ii}\n"
-                    fi
-                fi
-            done
-        done
-        device=$(echo -e "${devices}" | dmenu $DMENUSETTINGS)
+        device=$(get_mountable_devs | dmenu $DMENUSETTINGS)
 
         if [ -n "$device" ]; then
-            pmount $device
+            $mount_cmd $device
         fi
         ;;
     umount)
-        for i in $(mount | grep /media | cut -d " " -f 1); do
-            devices="${devices}${i}\n"
-        done
-
-        device=$(echo -e "${devices}" | dmenu $DMENUSETTINGS)
+        device=$(get_unmountable_devs | dmenu $DMENUSETTINGS)
 
         if [ -n "$device" ]; then
-            pumount $device
+            $umount_cmd "$device"
         fi
+        ;;
+    umount_all)
+        failed=0
+
+        if [ "$MOUNT_THING" == "udiskie" ]; then
+            for i in $(udiskie-info -a -f is_mounted); do
+                if ! umount_dev_is_auto_blocked "$i"; then
+                    # NOTE: $umount_cmd is udiskie_umount_wrapper which
+                    #       expects stuf to be mounted in /run/media
+                    # TODO: extend udiskie_umount_wrapper to accept two
+                    #       parameters
+                    udiskie-umount "$i"
+                    [ $? -ne 0 ] && failed=1
+                fi
+            done
+        elif [ "$MOUNT_THING" == "pmount" ]; then
+            for i in $(get_unmountable_devs); do
+                if ! umount_dev_is_auto_blocked "$i"; then
+                    $umount_cmd "$i"
+                    [ $? -ne 0 ] && failed=1
+                fi
+            done
+        fi
+
+        SAVEIFS=$IFS
+        IFS=$(echo -en "\n\b")
+        for i in $(mount | grep '^\(^\([0-9]\{1,3\}\.\)\{3\}[0-9]\{1,3\}:\)\|\(/\)[^ ]* on /[^ ]\+'); do
+            dev=$(echo $i | sed 's#\(/.*\?\) on /\([^/]\+/\)*\(.*\?\) type .*#\1#g;')
+            mp=$(echo $i | sed 's#\(/.*\?\) on \(/\([^/]\+/\)*\(.*\?\)\) type .*#\2#g;')
+            if ! mount_dev_is_blocked "$dev" && ! umount_dev_is_auto_blocked "$dev"; then
+                umount "$mp"
+                [ $? -ne 0 ] && failed=1
+            fi
+        done
+        IFS=$SAVEIFS
+
+        exit $failed
         ;;
     *)
         echo "fd-mm action"
diff --git a/scripts/fd-suspend b/scripts/fd-suspend
--- a/scripts/fd-suspend
+++ b/scripts/fd-suspend
@@ -4,26 +4,42 @@
 #set -e
 
 source ETCPREFIX/ferrydust/system.rc
+source LIBPREFIX/fd-functions
 
 function susprep {
+    fd-unotify -a ferrydust "Falling asleep..."
+
     logger -t suspend "sleeping down"
-    for A in $(ls /media/); do pumount $A; done;
+    fd-mount umount_all
+    if [ $? -ne 0 ]; then
+        logger -t suspend "Suspend failed due to unmounted file systems"
+        fd-unotify -a ferrydust "Suspend failed due to unmounted file systems"
+        exit 1
+    fi
+    umount -a -t nfs,cifs,davfs,smbfs
+    if [ $? -ne 0 ]; then
+        logger -t suspend "Suspend failed due to unmounted file systems"
+        fd-unotify -a ferrydust "Suspend failed due to unmounted file systems"
+        exit 1
+    fi
     $NET_DOWN
     BINPREFIX/fd-ulock &
     sleep 0.2
     sync
-    logger -t suspend "sleeping now"
+    logger -t suspend "sleeping now..."
 }
 
 function suspres {
     logger -t suspend "waking up"
     $NET_UP
     if [ "$(</sys/class/power_supply/AC/online)" -ne 1 ]; then
-        $(sleep 5; BINPREFIX/fd-pm down) &
+        { sleep 5; BINPREFIX/fd-pm down } &
     else
-        $(sleep 5; BINPREFIX/fd-pm up) &
+        { sleep 5; BINPREFIX/fd-pm up } &
     fi
     logger -t suspend "woken up"
+
+    fd-unotify -a ferrydust "Woken up"
 }
 
 to=$1
